// Code generated by goctl. DO NOT EDIT.
package types

type FileDownloadReq struct {
	FileName string `path:"filename"`
}

type FileDownloadResp struct {
}

type FileSlice struct {
	Hash  string `json:"hash"`
	Order uint8  `json:"order"`
}

type FileSliceDownloadReq struct {
	Hash string `path:"hash"`
}

type FileSliceDownloadResp struct {
}

type FileSliceUploadPrepareReq struct {
	FileName string `json:"filename"`
	Size     int64  `json:"size"`
	Hash     string `json:"hash"`
}

type FileSliceUploadPrepareResp struct {
	FileName string `json:"filename"`
	Size     int64  `json:"size"`
	Hash     string `json:"hash"`
}

type FileSliceUploadReq struct {
	FileHash string `form:"filehash"`
	Size     int64  `form:"size"`
	Order    uint8  `form:"order"`
}

type FileSliceUploadResp struct {
	Hash  string `json:"hash"`
	Order uint8  `json:"order"`
}

type FileUploadReq struct {
	FileName string `form:"filename"`
	Size     int64  `form:"size"`
}

type FileUploadResp struct {
	Hash       string      `json:"hash"`
	FileSlices []FileSlice `json:"fileslices"`
}

type GetFileInfoReq struct {
	Hash string `path:"hash"`
}

type GetFileInfoResp struct {
	Hash       string      `json:"hash"`
	FileSlices []FileSlice `json:"fileslices"`
}
