// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/YShiJia/IM/apps/social/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/entry/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/entry/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/chat/history/group",
					Handler: GetHistoryGroupChatHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/chat/history/private",
					Handler: GetHistoryPrivateChatHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/friend/add",
					Handler: AddFriendHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/friend/block",
					Handler: BlockFriendHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/friend/delete",
					Handler: DeleteFriendHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/friend/group",
					Handler: UpdateFriendGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/create",
					Handler: CreateGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/group/delete",
					Handler: DeleteGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/group/dismiss",
					Handler: DismissGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/group/member/delete",
					Handler: DeleteGroupMemberHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/group/member/list/:group_id",
					Handler: GetGroupMemberListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/user/info",
					Handler: ChangeUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/search/:search",
					Handler: SearchUserHandler(serverCtx),
				},
			}...,
		),
	)
}
