// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/YShiJia/IM/apps/file/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/file/download/:filename",
					Handler: FileDownloadHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/file/info/:hash",
					Handler: GetFileInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/file/slice/:hash",
					Handler: FileSliceDownloadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/slice/upload",
					Handler: FileSliceUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/slice/upload/prepare",
					Handler: FileSliceUploadPrepareHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/upload",
					Handler: FileUploadHandler(serverCtx),
				},
			}...,
		),
	)
}
