// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	status "github.com/YShiJia/IM/apps/status/api/internal/handler/status"
	"github.com/YShiJia/IM/apps/status/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取用户在线信息
				Method:  http.MethodGet,
				Path:    "/useronline",
				Handler: status.UseronlineHandler(serverCtx),
			},
			{
				// 获取连接信息
				Method:  http.MethodGet,
				Path:    "/wsconninfo",
				Handler: status.WsconninfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/status"),
	)
}
