// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	file "github.com/YShiJia/IM/apps/message/api/internal/handler/file"
	"github.com/YShiJia/IM/apps/message/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/file/check/:hash",
					Handler: file.FileCheckHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/download/:hash",
					Handler: file.FileDownloadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/upload",
					Handler: file.FileUploadHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)
}
