// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type FileCheckReq struct {
	Hash string `json:"hash",path:"hash"`
}

type FileCheckResp struct {
	Exists bool `json:"exists"`
}

type FileDownloadReq struct {
	Hash string `json:"hash",path:"hash"`
}

type FileDownloadResp struct {
	Data []byte `json:"data"`
}

type FileUploadReq struct {
	Hash     string `json:"hash,optional"`
	FileName string `json:"name,optional"`
	Size     int64  `json:"size,optional"`
}

type FileUploadResp struct {
	Hash string `json:"identity"`
}
