// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	SocialId string `json:"id"`
	Password string `json:"password"`
}

type LoginResp struct {
	User struct {
		SocialId string `json:"id"`
		Nickname string `json:"nickname"`
		Email    string `json:"email"`
	} `json:"user"`
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type RegisterReq struct {
	Nickname   string `json:"nickname"`
	Email      string `json:"email"`
	Password   string `json:"password"`
	RePassword string `json:"rePassword"`
}

type RegisterResp struct {
	User struct {
		SocialId string `json:"id"`
		Nickname string `json:"nickname"`
		Email    string `json:"email"`
	} `json:"user"`
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type User struct {
	SocialId string `json:"id"`
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
}

type UserInfoReq struct {
	SocialId string `json:"id"`
}

type UserInfoResp struct {
	Info struct {
		SocialId string `json:"id"`
		Nickname string `json:"nickname"`
		Email    string `json:"email"`
	} `json:"info"`
}

type WsConnInfoReq struct {
	SocialId string `json:"id"`
}

type WsConnResp struct {
	Address string `json:"address"`
}
