// Code generated by goctl. DO NOT EDIT.
package types

type UserOnlineReq struct {
	SocialIds []string `json:"socialIds"`
}

type UserOnlineResp struct {
	SocialIds []string `json:"socialIds"`
}

type WsConnInfoReq struct {
	SocialId string `json:"id"`
}

type WsConnResp struct {
	Address string `json:"address"`
}
